### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by bugy** [Nottt/script-server#1]
Hi @Nottt, I believe I'm doing smth wrong, but I cannot run the container :(

First, I was following the guide with `docker create ...`. But it just creates and image. Running this image didn't bind ports or volumes.

Then I replace `docker create` with `docker run` and in this case I got an error:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 1-settings: executing... 
[cont-init.d] 1-settings: exited 0.
[cont-init.d] 99-deps: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/99-deps: Permission denied
foreground: fatal: unable to wait for /var/run/s6/etc/cont-init.d/99-deps: No child process
```
I checked and my dependencies.sh file is executable (on the host machine)

Any ideas?

**Comment by Nottt** [comment]
Hi. The file on the host you mapped to 99-deps, what is it? Does it start with a shebang? It could be that...

I will try to reproduce this in a VPS soon.

**Comment by Nottt** [comment]
I can't reproduce your issue. I booted a VPS and ran my docker create command, then `docker start script server`

My `/host/path/to/dependencies.sh` file was just:

```sh
#!/bin/bash
echo Hey
```

It executed as expected.

**Comment by bugy** [comment]
Hi @Nottt, I'm really sorry, I messed up paths on my machine. After fixing them, everything works!
